# name should be unique if you want to publish it in the marketplace
name: 'Custom Action JavaScript'
description: 'An example of a custom action using JavaScript'
author: Pranav Suryawanshi
inputs:
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
    default: 'DEFAULT GITHUB TOKEN'
  TENOR:
    description: 'TENOR API token'
    required: true
    default: 'DEFAULT TENOR TOKEN'
    
outputs:
  github_tkn:
    description: 'Output of actions'
    # Not required otherwise will generate
    # required: true
    # default: 'Default value for output for actions'
    # commit to check concurrency 1
    # commit to check concurrency 2
runs:
  using: 'node20'
  main: 'src/index.js'
