name: GIthub Action output
on :  
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci-job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1Id.outputs.test}}
      output2: ${{steps.step2Id.outputs.test}}
      output3: ${{steps.step2Id.outputs.testt}}
    steps:
      - name: Stage1 from CI job1
        id: step1Id
        run: |
           echo "test=stage1" >> $GITHUB_OUTPUT

      - name: Stage2 from CI job2
        id: step2Id
        run: |
          echo "test=stage2" >> $GITHUB_OUTPUT 
          echo "testt=stage3" >> $GITHUB_OUTPUT

  cd-job:
    runs-on: ubuntu-latest
    needs: ci-job
    steps:
      - name: Step1 from cd job
        env:
          INPUT_TEST: ${{ needs.ci-job.outputs.output1 }}
        run: |
          echo "output from cd-job step: $INPUT_TEST"
          echo "below is output: ${{ needs.ci-job.outputs.output2 }}"
          echo "below is output3: ${{ needs.ci-job.outputs.output3 }}"

