name: GIthub Action output
on :  
  push:
    branches: [main]
  workflow_dispatch:

# jobs:
#   ci-job:
#     runs-on: ubuntu-latest
#     outputs:
#       output1: ${steps.step1Id.outputs.test}
#     steps:
#       - name: Stage1 from CI job1
#         id: step1Id
#         run: |
#            echo "test=stage1" >> $GITHUB_OUTPUT

#       - name: Stage2 from CI job2
#         id: step2Id
#         run: |
#           echo "test=stage2" >> $GITHUB_OUTPUT 

#   cd-job:
#     runs-on: ubuntu-latest
#     needs: ci-job
#     steps:
#       - name: Step1 from cd job
#         env:
#           INPUT_TEST: ${{ needs.ci-job.outputs.output1 }}
#         run: |
#           echo "output from cd-job step: ${INPUT_TEST}"
#           echo "below is output: ${{needs.ci-job.outputs.output1}}"


jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
