name: GIthub Action output
on :  
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci-job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${steps.stage1Id.outputs.test}
    steps:
      - name: Stage1 from CI job1
        id: stap1Id
        run: |
           echo "Hi there this is the output from stage1" >> $GITHUB_OUTPUT

      - name: Stage2 from CI job2
        id: step2Id
        run: |
          echo "Hi tehre this is the outpt from stage2" >> $GITHUB_OUPTUT 

  cd-job:
    runs-on: ubuntu-latest
    needs: ci-job
    steps:
      - name: Step1 from cd job
        run: |
          echo "output from cd-job step: ${{ needs.ci-job.outputs.output1 }}"
