name: Testing for custom actions

on :  
  push:
    branches: [main]
  workflow_dispatch:  

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: clone the repository
        uses: actions/checkout@v4

      - name: setup the node
        uses: actions/setup-node@v4
        with:
          node-version: 20   

      - name: print pwd
        run: pwd    

      - name: use cutsom actions
      # ./ => action.yml file is in current directory
        uses: ./ 

      - name: custom actions in different repository
        id: getActions
        uses: pranavjames/Custom-Action@v1
        with:
          GITHUB_TOKEN: 'GITHUB TOKEN FROM ANOTHER REPOSITORY'
          TENOR: 'TENOR API TOKEN FROM ANOTHER REPOSITORY' 
          
      - name: print github actions result
        run: |
          echo "output: ${{ steps.getActions.outputs.github_tkn }}"
        # uses: actions/checkout@v4
        # with:
        #   repository: pranavjames/custom-action-javascript
        #   ref: main
        #   path: custom-action-javascript     

